image: node

test_build:
  only:
    changes:
      - src/**/*
      - examples/**/*
      - .gitlab-ci.yml
      - elm.json
      - package.json
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  script:
    - yarn
    - yarn build:demo
